version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_hidden_from_binder
    container_name: jupyter
    ports:
    - 8888:8888
    volumes:
    - ./notebooks:/notebooks